--- 
- hosts: qaenv
  tasks:
  - name: Docker service start
    service: name=docker state=started enabled=yes
      
  - name: app-container
    docker_container:
      name: app
      image: 'http://192.168.100.10:5000/java-app'
      recreate: yes
      state: started
      ports:
      - "80:8080"
