--- 
#- hosts: qaenv
#  become: yes
#  tasks:  
#  - name: app-container
#    docker_container:
#      name: app
#      image: "192.168.100.10:5000/app:{{image_tag}}"
#      recreate: yes
#     state: started
#      ports:
#      - "80:8080"
 - name: Download new image and deploy it to qa servers
   hosts: qa
#   become: yes

   tasks:
   - name: Stop&delete old container
     shell: docker rm -f app
     ignore_errors: yes
     
   - name: Delete old image backup
     shell: docker rmi 192.168.100.10:5000/app:{{image_tag}}
     ignore_errors: yes
    
   - name: BackUP old image
     shell: docker tag 192.168.100.10:5000/app:{{image_tag}}
     ignore_errors: yes
    
   - name: Delete old image
     shell: docker rmi 192.168.100.10:5000/app:{{image_tag}}
     ignore_errors: yes

   - name: Pull new image from registry
     shell: docker pull 192.168.100.10:5000/app:{{image_tag}}

   - name: Run new image on 80 port
     shell: docker run -d -p 80:8080 --name app 192.168.100.10:5000/app:{{image_tag}}
