--- 
- hosts: qaenv
  tasks:
  - name:  Add Insecure Registry to Docker Engine
    lineinfile:
      dest: /etc/docker/daemon.json
      state: present
      regexp: '^{}'
      line: '{ "insecure-registries" : ["192.168.100.10:5000"]  }'
      
  - name: Docker service start
    service: name=docker state=restarted enabled=yes
      
  - name: app-container
    docker_container:
      name: app
      image: 'http://192.168.100.10:5000/java-app'
      recreate: yes
      state: started
      ports:
      - "80:8080"
