--- 
- hosts: qaenv
  tasks:
  - name: app-container
    docker_container:
      name: app
      image: 'http://192.168.100.10:5000/v2/_catalog/java-app'
      recreate: yes
      state: started
      ports:
      - "80:8080"
