---
  # - name: install packages
  #   yum: name={{ item }} state=present
  #   with_items:
  #     - epel-release
  #     - python2-pip
  #
  # - name: install docker-py
  #   pip:
  #     name: docker-py

  # - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
  #   shell: docker run -d -p 80:8080 --name app master:5000/app:{{ image_tag }}
  # #
  - name: remove container
    docker_container:
      name: app
      state: absent
      
  - name: app-container
    docker_container:
      name: app
      image: '192.168.100.10:5000/app:{{ image_tag }}'
      recreate: yes
      state: started
      ports:
      - "80:8080"
