---
- name: Deploy image
  tasks:    
  - name: app-container
    docker_container:
      name: app
      image: '192.168.100.10:5000/app:{{ image_tag }}'
      recreate: yes
      state: started
      ports:
      - "80:8080"
