---
- name: Install Docker
  hosts: all
  become: true
  
  tasks:
  - name: Add docker repo
    template:
      src: /vagrant/ansible/docker.repo
      dest: /etc/yum.repos.d/docker.repo

  - name: Install docker
    yum:
      name: docker-engine
      state: present
      
  - name: Start docker
    service:
      name: docker
      state: started

  - name: Enable docker
    systemd:
      name: docker
      enabled: yes
      
  - name: Admin access for docker user
    shell: sudo usermod -aG docker $(whoami)
    args:
      executable: /bin/bash
      
  - name: Add insecure registry
    shell: sudo cp ansible/daemon.json /etc/docker/
    args:
      executable: /bin/bash

  - name: install packages
    yum: name={{ item }} state=present
    with_items:
      - epel-release
      - python2-pip
  
  - name: install docker-py
    pip:
    name: docker-py
    
#  - name: add hosts
 #   shell:
  #    cmd: |
   #   sudo tee <<EOF
    #  192.168.100.10 master
     # 192.168.100.11 dev
     # 192.168.100.12 stage
     # 192.168.100.13 qa
     # EOF
      
